### ISSUE TITLE
Checklist for v1

### ISSUE THREAD

**Issue by MarkKremer** [gopxl/docs#1]
## v1
- [ ] Redirects work. E.g. from gopxl.github.io/beep to the first page of the first section. Alternatively, we have an index page.
- [ ] URL's and URL rewrites are final. Number prefixes and .html suffixes are stripped. Must work on the dev server too.
- [ ]Test with Markdown elements used in the Beep & Pixel docs.
- [ ] Code blocks without specified language have the proper styling.
- [ ] Make the action a composite action so it takes care of the GitHub Pages actions.

## Future
- [ ] Images are clickable. Opens either a popup with the full size image or the image on GitHub.
- [ ] Headings link to their own anchor.
- [ ] Allow some HTML in Markdown. E.g. `<br>`.
- [ ] Make UI work good on phones.
- [ ] Add good search.
- [ ] SEO
- [ ] Align logo better.
- [ ] Different logo's different projects.
- [ ] Other UI tweaks.
